export default [
  {
    id:1,  
    title: "Software Engineer",
    company_name: "Microsoft",
      location: "Seattle, Wa",
      status: "Screening",
      job_link: "link.com",
      candidates: 200,
      date_published: "January 20, 2021",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sapien elit faucibus bibendum proin ut. Arcu viverra mollis dolor neque imperdiet sit velit. Pellentesque. Arcu viverra mollis dolor neque imperdiet sit velit...",
  },
  {
    id:2,  
    title: "Software Engineer",
    company_name: "Microsoft",
      location: "Seattle, Wa",
      status: "Screening",
      job_link: "link.com",
      candidates: 200,
      date_published: "January 20, 2021",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sapien elit faucibus bibendum proin ut. Arcu viverra mollis dolor neque imperdiet sit velit. Pellentesque. Arcu viverra mollis dolor neque imperdiet sit velit...",
  },
  {
    id:3,  
    title: "Software Engineer",
    company_name: "Microsoft",
      location: "Seattle, Wa",
      status: "Screening",
      job_link: "link.com",
      candidates: 200,
      date_published: "January 20, 2021",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sapien elit faucibus bibendum proin ut. Arcu viverra mollis dolor neque imperdiet sit velit. Pellentesque. Arcu viverra mollis dolor neque imperdiet sit velit...",
  },
  {
    id:4,  
    title: "Software Engineer",
    company_name: "Microsoft",
      location: "Seattle, Wa",
      status: "Screening",
      job_link: "link.com",
      candidates: 200,
      date_published: "January 20, 2021",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sapien elit faucibus bibendum proin ut. Arcu viverra mollis dolor neque imperdiet sit velit. Pellentesque. Arcu viverra mollis dolor neque imperdiet sit velit...",
  },
  {
    id:5,  
    title: "Software Engineer",
    company_name: "Microsoft",
      location: "Seattle, Wa",
      status: "Screening",
      job_link: "link.com",
      candidates: 200,
      date_published: "January 20, 2021",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sapien elit faucibus bibendum proin ut. Arcu viverra mollis dolor neque imperdiet sit velit. Pellentesque. Arcu viverra mollis dolor neque imperdiet sit velit...",
  },
  {
    id:6,  
    title: "Software Engineer",
    company_name: "Microsoft",
      location: "Seattle, Wa",
      status: "Screening",
      job_link: "link.com",
      candidates: 200,
      date_published: "January 20, 2021",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sapien elit faucibus bibendum proin ut. Arcu viverra mollis dolor neque imperdiet sit velit. Pellentesque. Arcu viverra mollis dolor neque imperdiet sit velit...",
  },{
    id:7,  
    title: "Software Engineer",
    company_name: "Microsoft",
      location: "Seattle, Wa",
      status: "Screening",
      job_link: "link.com",
      candidates: 200,
      date_published: "January 20, 2021",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sapien elit faucibus bibendum proin ut. Arcu viverra mollis dolor neque imperdiet sit velit. Pellentesque. Arcu viverra mollis dolor neque imperdiet sit velit...",
  },
  {
    id:8,  
    title: "Software Engineer",
    company_name: "Microsoft",
      location: "Seattle, Wa",
      status: "Screening",
      job_link: "link.com",
      candidates: 200,
      date_published: "January 20, 2021",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sapien elit faucibus bibendum proin ut. Arcu viverra mollis dolor neque imperdiet sit velit. Pellentesque. Arcu viverra mollis dolor neque imperdiet sit velit...",
  },
  {
    id:9,  
    title: "Software Engineer",
    company_name: "Microsoft",
      location: "Seattle, Wa",
      status: "Screening",
      job_link: "link.com",
      candidates: 200,
      date_published: "January 20, 2021",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sapien elit faucibus bibendum proin ut. Arcu viverra mollis dolor neque imperdiet sit velit. Pellentesque. Arcu viverra mollis dolor neque imperdiet sit velit...",
  },{
    id:10,  
    title: "Software Engineer",
    company_name: "Microsoft",
      location: "Seattle, Wa",
      status: "Screening",
      job_link: "link.com",
      candidates: 200,
      date_published: "January 20, 2021",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sapien elit faucibus bibendum proin ut. Arcu viverra mollis dolor neque imperdiet sit velit. Pellentesque. Arcu viverra mollis dolor neque imperdiet sit velit...",
  },
  {
    id:11,  
    title: "Software Engineer",
    company_name: "Microsoft",
      location: "Seattle, Wa",
      status: "Screening",
      job_link: "link.com",
      candidates: 200,
      date_published: "January 20, 2021",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sapien elit faucibus bibendum proin ut. Arcu viverra mollis dolor neque imperdiet sit velit. Pellentesque. Arcu viverra mollis dolor neque imperdiet sit velit...",
  },
  {
    id:12,  
    title: "Software Engineer",
    company_name: "Microsoft",
      location: "Seattle, Wa",
      status: "Screening",
      job_link: "link.com",
      candidates: 200,
      date_published: "January 20, 2021",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sapien elit faucibus bibendum proin ut. Arcu viverra mollis dolor neque imperdiet sit velit. Pellentesque. Arcu viverra mollis dolor neque imperdiet sit velit...",
  },{
    id:13,  
    title: "Software Engineer",
    company_name: "Microsoft",
      location: "Seattle, Wa",
      status: "Screening",
      job_link: "link.com",
      candidates: 200,
      date_published: "January 20, 2021",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sapien elit faucibus bibendum proin ut. Arcu viverra mollis dolor neque imperdiet sit velit. Pellentesque. Arcu viverra mollis dolor neque imperdiet sit velit...",
  },
  {
    id:14,  
    title: "Software Engineer",
    company_name: "Microsoft",
      location: "Seattle, Wa",
      status: "Screening",
      job_link: "link.com",
      candidates: 200,
      date_published: "January 20, 2021",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sapien elit faucibus bibendum proin ut. Arcu viverra mollis dolor neque imperdiet sit velit. Pellentesque. Arcu viverra mollis dolor neque imperdiet sit velit...",
  },
  {
    id:15,  
    title: "Software Engineer",
    company_name: "Microsoft",
      location: "Seattle, Wa",
      status: "Screening",
      job_link: "link.com",
      candidates: 200,
      date_published: "January 20, 2021",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sapien elit faucibus bibendum proin ut. Arcu viverra mollis dolor neque imperdiet sit velit. Pellentesque. Arcu viverra mollis dolor neque imperdiet sit velit...",
  },{
    id:16,  
    title: "Software Engineer",
    company_name: "Microsoft",
      location: "Seattle, Wa",
      status: "Screening",
      job_link: "link.com",
      candidates: 200,
      date_published: "January 20, 2021",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sapien elit faucibus bibendum proin ut. Arcu viverra mollis dolor neque imperdiet sit velit. Pellentesque. Arcu viverra mollis dolor neque imperdiet sit velit...",
  },
  {
    id:17,  
    title: "Software Engineer",
    company_name: "Microsoft",
      location: "Seattle, Wa",
      status: "Screening",
      job_link: "link.com",
      candidates: 200,
      date_published: "January 20, 2021",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sapien elit faucibus bibendum proin ut. Arcu viverra mollis dolor neque imperdiet sit velit. Pellentesque. Arcu viverra mollis dolor neque imperdiet sit velit...",
  },
  {
    id:18,  
    title: "Software Engineer",
    company_name: "Microsoft",
      location: "Seattle, Wa",
      status: "Screening",
      job_link: "link.com",
      candidates: 200,
      date_published: "January 20, 2021",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sapien elit faucibus bibendum proin ut. Arcu viverra mollis dolor neque imperdiet sit velit. Pellentesque. Arcu viverra mollis dolor neque imperdiet sit velit...",
  },{
    id:19,  
    title: "Software Engineer",
    company_name: "Microsoft",
      location: "Seattle, Wa",
      status: "Screening",
      job_link: "link.com",
      candidates: 200,
      date_published: "January 20, 2021",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sapien elit faucibus bibendum proin ut. Arcu viverra mollis dolor neque imperdiet sit velit. Pellentesque. Arcu viverra mollis dolor neque imperdiet sit velit...",
  },
  {
    id:20,  
    title: "Software Engineer",
    company_name: "Microsoft",
      location: "Seattle, Wa",
      status: "Screening",
      job_link: "link.com",
      candidates: 200,
      date_published: "January 20, 2021",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sapien elit faucibus bibendum proin ut. Arcu viverra mollis dolor neque imperdiet sit velit. Pellentesque. Arcu viverra mollis dolor neque imperdiet sit velit...",
  },
  {
    id:21,  
    title: "Software Engineer",
    company_name: "Microsoft",
      location: "Seattle, Wa",
      status: "Screening",
      job_link: "link.com",
      candidates: 200,
      date_published: "January 20, 2021",
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sapien elit faucibus bibendum proin ut. Arcu viverra mollis dolor neque imperdiet sit velit. Pellentesque. Arcu viverra mollis dolor neque imperdiet sit velit...",
  },
];
