import tmpRadio from "./Radio";
import tmpInput from "./Input";
import tmpModal from "./Modal";
import tmpButton from "./Button";
import tmpSelect from "./Select";
import tmpSpinner from "./Spinner";
import tmpLocation from "./Location";
import tmpCheckbox from "./Checkbox";
import tmpSelectNew from "./SelectNew";
import tmpUserAvatar from "./UserAvatar";
import tmpAsyncSelect from "./AsyncSelect";
import tmpFlashMessage from "./FlashMessage";
import tmpMessageHelper from "./MessageHelper";
import tmpConfirmDialog from "./ConfirmDialog";
import tmpErrorTextHelper from "./ErrorTextHelper";
import tmpProfileImageCrop from "./ProfileImageCrop";
import tmpSingleFileDropZone from "./SingleFileDropZone";
import tmpAsyncCreatableSelect from "./AsyncCreatableSelect";
import tmpEditableText from "./EditableText/EditableText";
import tmpPageTitle from "./PageTitle";
import tmpAccordion from "./Accordion";
import tmpTabs from "./Tabs";
import tmpListItem from "./ListItem";

export const Input = tmpInput;
export const Modal = tmpModal;
export const Radio = tmpRadio;
export const Select = tmpSelect;
export const Button = tmpButton;
export const Spinner = tmpSpinner;
export const Checkbox = tmpCheckbox;
export const Location = tmpLocation;
export const SelectNew = tmpSelectNew;
export const UserAvatar = tmpUserAvatar;
export const AsyncSelect = tmpAsyncSelect;
export const FlashMessage = tmpFlashMessage;
export const ConfirmDialog = tmpConfirmDialog;
export const MessageHelper = tmpMessageHelper;
export const ErrorTextHelper = tmpErrorTextHelper;
export const ProfileImageCrop = tmpProfileImageCrop;
export const SingleFileDropZone = tmpSingleFileDropZone;
export const AsyncCreatableSelect = tmpAsyncCreatableSelect;
export const EditableText = tmpEditableText;
export const PageTitle = tmpPageTitle;
export const Accordion = tmpAccordion;
export const ListItem = tmpListItem;
export const Tabs = tmpTabs;
